name: Test
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { miniforge-variant: "Mambaforge", miniforge-version: "latest" }
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f environment.yml
          conda list
      - name: Install pplpy
        shell: bash -l {0}
        run: |
          pip install --verbose --no-index --no-build-isolation .
      - name: Run tests
        shell: bash -l {0}
        run: |
          python setup.py test
      - name: Show logs
        run: grep "" /dev/null `find -name '*.log'` || true
        if: ${{ always() }}
